version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "github-actions"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "gradle"
