version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/
    working_dir: /frontend/
    image: fl-online-demo-frontend
    env_file:
      - ./frontend/api_hosts.env
  backend:
    build:
      context: ./backend/
    image: fl-online-demo-backend
