services:
  frontend:
    build:
      target: dev
    volumes:
      - type: bind
        source: ./frontend/
        target: /frontend/
    command:
      - sh
      - -c
      - |
        [ -d node_modules/ ] || {
          npm ci
        }
        npm run dev
  backend:
    build:
      target: dev
    volumes:
      - type: bind
        source: ./backend/
        target: /backend/
    command:
      - ./gradlew
      - bootRun
  nginx:
    command:
      - nginx-debug
      - -g
      - daemon off;
