services:
  frontend:
    build:
      context: ./frontend/
    working_dir: /frontend/
    image: fl-online-demo-frontend
    volumes:
      - type: bind
        source: ./presets/myersTriangle/src.java
        target: /frontend/public/default-src.java
        read_only: true
      - type: bind
        source: ./presets/myersTriangle/test.java
        target: /frontend/public/default-test.java
        read_only: true
    restart: always
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: ./backend/
    working_dir: /backend/
    image: fl-online-demo-backend
    volumes:
      - type: bind
        source: ./util/HealthCheck.java
        target: /HealthCheck.java
        read_only: true
    restart: always
    healthcheck:
      test: ["CMD", "java", "/HealthCheck.java", "||", "exit", "1"]
      start_period: 30s
  kdemo:
    build: https://github.com/kusumotolab/kGenProg-online-demo.git#8d8ceb60d344acc86515b4863ce69ef00e699ae6
    restart: always
  nginx:
    image: nginx:1.21.6
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    restart: always
    ports:
      - 3000:80
    depends_on:
      - backend
      - frontend
